name: Fixed Cucumber Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java 17 (LTS)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Force Java 17 Compatibility
      run: |
        sed -i '/<maven.compiler.source>/!b;n;c\        <maven.compiler.source>17</maven.compiler.source>' pom.xml
        sed -i '/<maven.compiler.target>/!b;n;c\        <maven.compiler.target>17</maven.compiler.target>' pom.xml
        sed -i '/<maven.compiler.release>/!b;n;c\        <maven.compiler.release>17</maven.compiler.release>' pom.xml || true
        cat pom.xml | grep -A 3 "maven.compiler" || true

    - name: Run Tests
      run: mvn clean verify -Dheadless=true -B

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          target/cucumber-reports.html
          target/surefire-reports/
